FROM nginx:latest

# Copy custom HTML file to nginx HTML directory
COPY index.html /usr/share/nginx/html/

# Expose port 80
EXPOSE 80

# Modify default nginx configuration to use environment variable for background color
CMD sed -i "s/background-color: #ffffff;/background-color: $bgcolor;/g" /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'
