apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <removed for brevity>
    server: https://192.168.56.50:6443
  name: kubernetes
- cluster:
    certificate-authority-data: <removed for brevity>
    server: https://api.crc.testing:6443
  name: api-crc-testing:6443  
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
- context:
    cluster: api-crc-testing:6443
    namespace: default
    user: kubeadmin/api-crc-testing:6443
  name: default/api-crc-testing:6443/kubeadmin
current-context: kubernetes-admin@kubernetes
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: <removed for brevity>
    client-key-data: <removed for brevity>
- name: kubeadmin/api-crc-testing:6443
  user:
    token: <removed>



