# grafana-instnace.yaml
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  labels:
    dashboards: grafana-a
    folders: grafana-a
  name: grafana-a
  namespace: monitoring
spec:
  config:
    auth:
      disable_login_form: 'false'
    log:
      mode: console
    security:
      admin_password: start
      admin_user: root
# ---
# apiVersion: grafana.integreatly.org/v1beta1
# kind: GrafanaDashboard
# metadata:
#   name: grafanadashboard-sample
# spec:
#   instanceSelector:
#     matchLabels:
#       dashboards: grafana-a
#   json: |
#     {

#       "id": null
#       "title": "Simple Dashboard"
#       "tags": []
#       "style": "dark"
#       "timezone": "browser"
#       "editable": true
#       "hideControls": false
#       "graphTooltip": 1
#       "panels": []
#       "time": {
#         "from": "now-6h"
#         "to": "now"
#       }
#       "timepicker": {
#         "time_options": []
#         "refresh_intervals": []
#       }
#       "templating": {
#         "list": []
#       }
#       "annotations": {
#         "list": []
#       }
#       "refresh": "5s"
#       "schemaVersion": 17
#       "version": 0
#       "links": []
#     }