apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: node-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: node-exporter
  endpoints:
    # - port: metrics
      # targetPort: 9100
      # interval: 30s
    - port: web
      interval: 30s
  namespaceSelector:
    matchNames:
      - monitoring
