# ca/elastic-hamster-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-hamster
  namespace: ca-demo
spec:
  selector:
    matchLabels:
      app: elastic-hamster
  replicas: 7
  template:
    metadata:
      labels:
        app: elastic-hamster
    spec:
      serviceAccountName: elastic-hamster
      containers:
        - name: hamster
          image: quay.io/iamgini/elastic-hamster:1.0
          resources:
            requests:
              cpu: 500m
              memory: 50Mi
          env:
            - name: TOTAL_HAMSTER_USAGE
              value: "1.0"
