# pod-with-pullsecret.yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-container
      image: your-registry.com/your-image:tag
  imagePullSecrets:
    - name: my-registry-secret
