# services/one-page-service-clusterip.yaml
apiVersion: v1
kind: Service
metadata:
  name: one-page-clusterip
  namespace: svc-demo
spec:
  type: ClusterIP
  selector:
    app: onepage
  ports:
    - port: 8080      # Port exposed within the cluster
      targetPort: 80  # Port on the pods
      protocol: TCP   # Protocol
