# services/one-page-service-nodeport.yaml
apiVersion: v1
kind: Service
metadata:
  name: one-page-nodeport
  namespace: svc-demo
spec:
  type: NodePort
  selector:
    app: onepage
  ports:
    - port: 8080
      nodePort: 31001
      protocol: TCP
      targetPort: 80
