# ca/todo-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: todo-app
  namespace: ca-demo
spec:
  type: ClusterIP
  selector:
    app: todo
  ports:
    - port: 8081          # Port exposed within the cluster
      targetPort: 3000    # containerPort on the pods
