# mysql-secret.yaml
apiVersion: v1
items:
- apiVersion: v1
  data:
    MYSQL_PASSWORD: bXlzcWxwYXNzd29yZA==
    MYSQL_ROOT_PASSWORD: bXlzcWxyb290
    MYSQL_USER: bXlzcWx1c2Vy
  kind: Secret
  metadata:
    name: mysql-secret
    namespace: mysql
  type: Opaque
kind: List
metadata:
  resourceVersion: ""