# mysql-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: bXlzcWxyb290
  MYSQL_USER: bXlzcWx1c2Vy
  MYSQL_PASSWORD: bXlzcWxwYXNzd29yZA==
