# admission-controller.yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: admission-controllers

---
apiVersion: v1
kind: Secret
metadata:
  name: admission-controller-secret
  namespace: admission-controllers
type: kubernetes.io/tls
data:
  # The following fields need to be base64 encoded
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVEekNDQXZlZ0F3SUJBZ0lVY0JzR0tlVXh5K3NwMzdPWjFPcTRkc3pmUlVFd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0dqRVlNQllHQTFVRUF3d1BiWGt0WVdSdGFYTnphVzl1TFdOaE1CNFhEVEkwTVRBeU5qRTVNelF3TVZvWApEVEkxTVRBeU5qRTVNelF3TVZvd2dhUXhDekFKQmdOVkJBWVRBbE5ITVJJd0VBWURWUVFJREFsVGFXNW5ZWEJ2CmNtVXhFakFRQmdOVkJBY01DVk5wYm1kaGNHOXlaVEVZTUJZR0ExVUVDZ3dQVFhrZ1QzSm5ZVzVwZW1GMGFXOXUKTVJZd0ZBWURWUVFMREExSlZDQkVaWEJoY25SdFpXNTBNVHN3T1FZRFZRUUREREpoWkcxcGMzTnBiMjR0WTI5dQpkSEp2Ykd4bGNpMXpkbU11WVdSdGFYTnphVzl1TFdOdmJuUnliMnhzWlhKekxuTjJZekNDQVNJd0RRWUpLb1pJCmh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBSzFMUU15SnczT3lKQklPV3pWVC85UldqZkYvRzQxZW9ZbjcKVEFUNGszT1lDb0JST08xSjdySGg2MjVUSGlPR3o0bDNtMExsSWRTaWtVaGVkZXQ0V0VpT2hqZnFpUlZHN3VOMwpkalQ5YzhTY2g2bVo4WHJMWUZ2SEh4MlBuK29nclNKQ2hkVE1Qd0ZXOFNZS2hBMWNMMmFLbWQvUkkrV1gyQW0wCkJ3Y29lRXhjUU4xa2ViL1N5MGFQOTRsKzczL1Jpc3htcW44V1FFR2VqWHF3Z1pZcStaSTdUQ1Q0YnJMOTdCemUKa2VucjZ3YjJUNTNyQ0crejhHcXR4QlFhdElqM3JaNEphS3dLNnl0NkxMaXBjL05DNDQ1TnIvZXAyLzhwYVZUTAozME1QcmFWbDNmK0dza1ZEWk9sZG14M3ZSNDgrMnNhbmtPVkI5MlBYK2Zjb2RHMTBkSEVDQXdFQUFhT0J3VENCCnZqQU9CZ05WSFE4QkFmOEVCQU1DQmFBd0V3WURWUjBsQkF3d0NnWUlLd1lCQlFVSEF3RXdWd1lEVlIwUkJGQXcKVG9JWVlXUnRhWE56YVc5dUxXTnZiblJ5YjJ4c1pYSXRjM1pqZ2pKaFpHMXBjM05wYjI0dFkyOXVkSEp2Ykd4bApjaTF6ZG1NdVlXUnRhWE56YVc5dUxXTnZiblJ5YjJ4c1pYSnpMbk4yWXpBZEJnTlZIUTRFRmdRVXhsdlhVQlhJCkwrOTd3TXhMZ2FqZzVjOHlSOUV3SHdZRFZSMGpCQmd3Rm9BVUxDU2tOc2E3clpZRU1nWGVvZkVEQTMrRFdwb3cKRFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUkvQmxqZ2Y0cFVHOW9EVXFyb0pDVUJGRHAyN3lrRkFpbmJBMG5BVgpSWlJTeUpiNFgxRjlWQUVKY1A0bW5lc1p2NmhiN0VwQlBmNG10Y0RJWDhseVgzU3BLYzY3YU9NYmhDYjl6YTJzCmFrcUNnbFdmaVM5aHRyM2h2TWlEeHdUQzk2dFRRZnZ4ejZGclRJR3FFQjR2cWF4QkFPYXpCRlBJaXp5QmlXaGsKckc5S2ZqYTZJMXZOdUFXcU13Q3RoN21CZGJoM0J4T1pTVmN6c1BpSlZWLzkyc0ZLaHozVUZ5OGRSaEorVDF4SAoxOGhPNVFFblRiK2hRV2tpYnZ6WnJ0Umg4amZJK3l3T0hDQlczMXFqM2kyNmpsT1Y3TC9zQWtqcUg0anZZQVBYClFwemhPQkZrYWphRzlXbWJJdkE1dFFFWFR3OXU0ekVENkgrTGcwTFFmNUZ0SzRZPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV1Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktRd2dnU2dBZ0VBQW9JQkFRQ3RTMERNaWNOenNpUVMKRGxzMVUvL1VWbzN4Znh1TlhxR0orMHdFK0pOem1BcUFVVGp0U2U2eDRldHVVeDRqaHMrSmQ1dEM1U0hVb3BGSQpYblhyZUZoSWpvWTM2b2tWUnU3amQzWTAvWFBFbkllcG1mRjZ5MkJieHg4ZGo1L3FJSzBpUW9YVXpEOEJWdkVtCkNvUU5YQzltaXBuZjBTUGxsOWdKdEFjSEtIaE1YRURkWkhtLzBzdEdqL2VKZnU5LzBZck1acXAvRmtCQm5vMTYKc0lHV0t2bVNPMHdrK0c2eS9ld2MzcEhwNitzRzlrK2Q2d2h2cy9CcXJjUVVHclNJOTYyZUNXaXNDdXNyZWl5NApxWFB6UXVPT1RhLzNxZHYvS1dsVXk5OURENjJsWmQzL2hySkZRMlRwWFpzZDcwZVBQdHJHcDVEbFFmZGoxL24zCktIUnRkSFJ4QWdNQkFBRUNnZjk5SzJ1bkxSR2dGcUx1REdkd2F6ZGk5ZXNIeU5WOTNpRDk0Q1dmZzlxUHpTSTIKWDAveFhuRHo3LytaSXVjVVhabEtObkVxZDAxaGUyWnJ5SVhhK0RzNkNMZzcvWXdpQklOdEcrRTRKVFZRWlJzWQpXRXV6NGJ1OGp2Y21EQ1ZvRGlrQUk3cFpZMlREaFR0RktCTlZONm55NjZEQ2hOSlNDSHVIejlnTTJDRERLbmdVCjl1dzRtc3dDVUlqRFJDdE11bnVnUklSZjA1VlNUV1VjeHVwMDJGdDV5dzRXMGtFQnpzYU9WQXB5aHU5QVdaUWUKa0NyZjNGUDJUTFJ4MFMzbnpETmhRcnJaWDhUWVJ0djd6S1ozWTNJU3JKK09Qcms0WnRFUno4ODJ0bVMrajRsdwpaUnhYcEppRitqWkFKVVoxSVkvNGc1d2FlK05BUUhBRHRMWS9XQUVDZ1lFQTI0TXY2YjhScHJHdk5PRW8vTTJlClJpbVROMmVhOW53czNhcUIvL1orcGsvdXdyQVAwM2RlSzYzd2hseHM4NlV0cWhBay8vRDVIN1JoRjJpbG9IYnAKNDdHOUxwS3pmczM0dUV6VldwSkVlZm9VSVBmdkhKMlJRYyt6dGsvT25kTmxMeWV6NWZSdTNCczYwUTVXRTBFRgo0RWdHaFZmSmZuam1GTk1GRS9FMEpBRUNnWUVBeWhsYUFxNGVmb2wvNlpaSzZ0RXlENXc1YmMxb1Q0WkRodkVMCitzTHZ6WnhUd3o5Vld0SlNBUXhxY0FuT0N5VXFqMlZIcHFHbDhQa1NMRGhySkRvOEhxd3lYUm9wWm1CQ3Y0bSsKelFvRU1oc2tURFBCTHpsRm9SNmRqbVowYVBSbnlBa1hMM2hPaHFXS0V6SUpRb0J3azRJMDhrV2ZEU3lEYS9xdApqdUV3a0hFQ2dZQU9CSFdWenA2NDcxWEo0YXIxWWNmK29QOEdwYllPa1dWb0RsQlk0UXU3WVJWVkYxc2JYTjhGCm1Ram4rNVQxaGhIQmIyQjllNHpkQ202OHlQRHlxMFZLUmZwWHRBU0VUM0RYakFoL3pTRlVUTFRtV2c3SjNBSC8KbXR6V0FvaW1LVzZuc1RoYXNkNDJiZ0syZ056Y1ErVzFLY1JJMVk5SFpUOEVDMm1pbVYrRUFRS0JnQjNNVlNBMgpDaHNBTFJNRTdQRG9mV2dkMGIzbDNtNXpUbnVVQ1A4bFJQUmRDMkNyY3V0Y1BXa1lLbzF3ZEtmaUIvOXlvSGpxCk5xeHNIUWpXSEw0UHRCT1ZzaXRXRXlxY0lOdGE5UDRJYnd2d1FvN1Z4ck11ejV4dEJqQWIzU2dvZVREZVhrUEsKaWxHQ0VQUzVtUEhzUEMwVHNyalNHUng1SnJ1Q0Q1c1Vpdk9SQW9HQUNQT0Q4d2ZXUGsrVDRibVkyRzB3RCtXYgpxMUZLbTNjZ3JJSmVFYmxUQ2lNandnNERCWjkxbkxZcDhiUVVXbjhiSVgrWWlHeXE4MUt6VXk5ZFZaT3p5cFMwClVWUVBNNVlxbEszTDgreGUyQU5XSGZQME9sOUxzKzBweUhMc1g3WDh3NTBXWU40YVFOTjUwbVJFN1JpQ2Y3WHYKdzUreGdRbm0reXZZNkhrbDFMaz0KLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQo=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admission-controller
  namespace: admission-controllers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admission-controller
  template:
    metadata:
      labels:
        app: admission-controller
    spec:
      containers:
        - name: admission-controller
          image: quay.io/iamgini/k8s-admission-controller:1.5
          ports:
          - containerPort: 443
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
            requests:
              memory: "64Mi"
              cpu: "50m"
          volumeMounts:
            - name: certs
              mountPath: /app/certs
      volumes:
        - name: certs
          secret:
            secretName: admission-controller-secret
---
apiVersion: v1
kind: Service
metadata:
  name: admission-controller-svc
  namespace: admission-controllers
spec:
  ports:
    - port: 443
      targetPort: 443
  selector:
    app: admission-controller
