# nginx-service-nodeport.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-nodeport
spec:
  selector:
    app: nginx
    environment: test
  type: NodePort
  ports:
    - nodePort: 30001
      port: 80
      targetPort: 80
