# nginx-with-basic-adapter.yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-adapter
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: log-volume
      mountPath: /var/log/nginx
  - name: log-converter
    image: log-converter-image:latest
    #to be replaced with the correct log collection agent image

    volumeMounts:
    - name: log-volume
      mountPath: /var/log/nginx
  volumes:
  - name: log-volume
    emptyDir: {}
