# nginx-with-adapter.yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-adapter
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - name: log-volume
          mountPath: /var/log/nginx
    - name: fluentd-adapter
      image: fluent/fluentd:latest
      volumeMounts:
        - name: log-volume
          mountPath: /var/log/nginx
      resources:
        requests:
          memory: "100Mi"
          cpu: "50m"
  volumes:
    - name: log-volume
      emptyDir: {}
