# pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-hostpath-pvc
  namespace: pv-ns
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  # volumeMode: Filesystem
  selector:
    matchLabels:
      type: hostpath
      env: prod
  storageClassName: slow
